### PR TITLE
Add Unity Explorer

### PR DESCRIPTION
**Pull request by arthomnix**
Unity Explorer is a tool for exploring and modifying the internals of Unity games (including KSP2) on the fly, useful for mod developers or just for poking around in the game's internals.

### CODE REVIEW

**Comment by HebaruSan** [comment]
Hi @Falki-git, there's some interest in having Unity Explorer in CKAN, and we've heard that your fork is the preferred one among KSP2 modders. Would it be OK with you if we added it? Adding the original fork has issues with trying to get informed consent from someone who doesn't care about KSP2 or CKAN.

Side note that the `swinfo.json` has a broken `version_check` link, so we'd have to take the newly added `$vref` back out for this to work.

image

**Comment by cheese3660** [comment]
It seems as if @Falki-git does not put the remote swinfo in the repository? (Referencing the netkan error)

**Comment by jan-bures** [comment]
Yep, I just submitted a PR for that: https://github.com/Falki-git/UnityExplorer/pull/1

**Comment by cheese3660** [comment]
That should be everything, shall I go ahead and merge this?

**Comment by Falki-git** [comment]
@HebaruSan, of course, we can add that fork of Unity Explorer to CKAN.
Additionally, we've agreed to transfer ownership to KSP2Community org, so the new link to the source code is:
https://github.com/KSP2Community/UnityExplorer

What else is needed to make this happen?

**Comment by Falki-git** [comment]
> That should be everything, shall I go ahead and merge this?

Please do.

**Comment by cheese3660** [comment]
Got it, and I already edited the netkan to point to the org

**Review by HebaruSan — APPROVED** [review]
@cheese3660 Sure, go ahead. 👍

**Pull request merged**
