### PR TITLE
Fix SpaceWarp

### PR DESCRIPTION
**Pull request by arthomnix**
Fixes broken SpaceWarp metadata which causes KSP2 to not launch correctly.

### CODE REVIEW

**Comment by HebaruSan** [comment]
Glancing at this, I don't think we can make these changes. Some mods depend on only BepInEx and others depend on SpaceWarp, and it's a non-starter to make them conflict with each other.

**Comment by HebaruSan** [comment]
Can you please submit an issue describing what the problem is, so we can work out a solution?

**Comment by arthomnix** [comment]
I've made SpaceWarp provide BepInEx so that shouldn't be an issue

**Comment by HebaruSan** [comment]
It will be an issue:

1. User installs a mod that depends only on BepInEx
2. BepInEx is installed as a dependency
3. User tries to install a mod that depends on SpaceDock
4. It doesn't work

**Pull request closed without merging**
