### PR TITLE
UITK for KSP2: Fix the install paths and dependency on BepInEx

### PR DESCRIPTION
**Pull request by jan-bures**

### CODE REVIEW

**Review by HebaruSan — APPROVED** [review]
Thanks for the updates!

**Comment by HebaruSan** [comment]
@jan-bures, you already understand YAML and how CKAN works. I'd like to add you to the metadata wranglers team so you can make edits like this to future pull requests inline rather than having to make a separate PR. Would you mind?

**Comment by jan-bures** [comment]
Well, my understanding of CKAN is very surface level, but I can try to help out wherever I can.

**Comment by HebaruSan** [comment]
🎉 

Don't worry, we're seeking people willing to learn, not experts (since there aren't any 😆).
I need to do some legwork to get you added to the team, but expect that soon™️.

**Comment by HebaruSan** [comment]
OK, it it looks like that went through! 🎉 

image

You should now be able to make edits on these pull requests (and merge them to `main`, but I'd appreciate having a chance to take a glance first for a month or two while you're getting acclimated). See this quick reference wiki for more info:

https://github.com/KSP-CKAN/CKAN/wiki/How-to-Wrangle-Metadata-for-KSP2

Welcome aboard!

**Pull request merged**
