### PR TITLE
Add ShadowUtilityLIB depends to CheatsMenu

### PR DESCRIPTION
**Pull request by NathanPeake**
Added missing dependency ShadowUtilityLIB

### CODE REVIEW

**Comment by NathanPeake** [comment]
Requires #20

**Comment by HebaruSan** [comment]
You should mention this on SpaceDock so users know they need to install it.

https://spacedock.info/mod/3266/Cheats%20Menu

image

**Comment by HebaruSan** [comment]
You should also mention it on the forum thread.

https://forum.kerbalspaceprogram.com/index.php?/topic/214242-cheat-menu/

image

**Comment by HebaruSan** [comment]
You should also mention it in the README on GitHub and/or in the download.

https://github.com/Bit-Studios/CheatMenu

image

image

**Comment by NathanPeake** [comment]
> Hi @NathanPeake, thanks for letting us know about this. For what it's worth, we set the dependencies of CKAN by looking in the same places users would...
> 
> You should mention this on SpaceDock so users know they need to install it.
> 
> https://spacedock.info/mod/3266/Cheats%20Menu
> 
> image

Thanks @HebaruSan for reminding me to update them areas.

**Review by HebaruSan — APPROVED** [review]
Thanks for the update!

**Pull request merged**
