### PR TITLE
Update QuestariaAereospace.netkan

### PR DESCRIPTION
**Pull request by cheese3660**
Adds a dependency on patch manager, which was recently added to Questaria Aerospace

- <https://spacedock.info/mod/3444/Questaria%20Aerospace>
- <https://forum.kerbalspaceprogram.com/topic/219006-v111-questaria-aerospace-general-parts-mod-for-ksp2/>

### CODE REVIEW

**Comment by cheese3660** [comment]
The heck did I mess up here?
image

**Comment by HebaruSan** [comment]
It's something with the swinfo.json file, haven't taken a look at it yet...

```
1780 [1] FATAL CKAN.NetKAN.Program (null) - Object reference not set to an instance of an object.
1847 [1] FATAL CKAN.NetKAN.Program (null) -    at CKAN.NetKAN.Transformers.SpaceWarpInfoTransformer.<Transform>d__3.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at CKAN.NetKAN.Transformers.NetkanTransformer.Transform(Metadata metadata, TransformOptions opts)
   at CKAN.NetKAN.Processors.Inflator.<>c__DisplayClass1_0.<Inflate>b__0(Metadata netkan)
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`3.GetEnumerator()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CKAN.NetKAN.Processors.Inflator.Inflate(String filename, Metadata[] netkans, TransformOptions opts)
   at CKAN.NetKAN.Program.Main(String[] args)
```

**Comment by HebaruSan** [comment]
Whatever that error is, it's already live in production without these changes.

image

image

**Comment by cheese3660** [comment]
For reference here is the swinfo.json from the latest download
```json
{
  "spec": "2.0",
  "mod_id": "QuestariaAerospace",
  "name": "Questaria Aerospace",
  "author": "IsaQuest",
  "description": "Parts for Exploration",
  "source": "",
  "version": "1.1.1",
  "dependencies": [
    {
      "id": "com.github.x606.spacewarp",
      "version": {
        "min": "1.7.0",
        "max": "*"
      }
    },
		{
      "id":  "PatchManager",
      "version": {
        "min": "0.7.2",
        "max": "*"
      }
    },
    {
      "id": "lfo",
      "version": {
        "min": "1.0.0",
        "max": "*"
      }
    }
  ],
  "conflicts": []
}
```

**Comment by cheese3660** [comment]
Wait, hmm, I edited it out cuz it looked like a formating error, but the indentation before the `{` before `"id": "PatchManager"` is 2 tabs not spaces

**Comment by jan-bures** [comment]
Plus, I see that KSP2 version info is missing, whether that has anything to do with the error or not

**Comment by HebaruSan** [comment]
> Plus, I see that KSP2 version info is missing, whether that has anything to do with the error or not

Yes, I think `SpaceWarpInfoTransformer` is throwing here because `ksp2_version` is null:

```csharp
                    if (GameVersion.TryParse(swinfo.ksp2_version.min, out GameVersion minVer)
                        || GameVersion.TryParse(swinfo.ksp2_version.max, out maxVer))
```

**Comment by cheese3660** [comment]
So, I know why that likely wasn't set
It's a bug that I fixed today with KSP2 Unity Tools

**Comment by HebaruSan** [comment]
Is `ksp2_version` intended to be required in the swinfo spec? I don't think that was something I considered explicitly when writing the above code. If it's supposed to be required, we can add an explicit check and clear error message for it. Otherwise we can make that line more forgiving of nulls.

**Comment by cheese3660** [comment]
```cs
[JsonProperty("ksp2_version", Required = Required.DisallowNull)]
public SupportedVersionsInfo SupportedKsp2Versions { get; internal set; } = new()
{
    Min = "*",
    Max = "*"
};
```
It's defined as being allowed to be missing, or to have a non-null value, with the default being unbounded compatibility

**Comment by cheese3660** [comment]
Alright issue has been fixed mod-side, will merge now

**Pull request merged**
